#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
Index.title=Ajax Examples

AutoCompletePage.title=Auto-Complete TextField Example
AutoCompletePage.description=shows a text field with auto complete drop down like google suggest

ChoicePage.title=Drop Down Choice Example
ChoicePage.description=demonstrates the linked select boxes usecase

ClockPage.title=Clock Example
ClockPage.description=demonstrates a self-updating component via AjaxSelfUpdatingTimerBehavior

EditableLabelPage.title=Editable Label Example
EditableLabelPage.description=shows a label that can be edited inline via ajax

EffectsPage.title=Effects Example
EffectsPage.description=shows how to link wicket component updates with jQuery UI effects

FormPage.title=Form Example
FormPage.description=shows ajax form processing

GuestBook.title=Guest book Example
GuestBook.description=shows how a simple commenting system can be turned into ajax extravaganza.

LazyLoadingPage.title=LazyLoading Example
LazyLoadingPage.description=demonstrates lazy loading of components.

LinksPage.title=Links Example
LinksPage.description=demonstrates ajax enabled links

FileUploadPage.title=File Upload Example
FileUploadPage.description=demonstrates transparent ajax handling of a multipart form

ModalDialogPage.title=Modal dialog
ModalDialogPage.description=javascript modal dialog example

OnChangeAjaxBehaviorPage.title=On Change Ajax Updater Example
OnChangeAjaxBehaviorPage.description=demonstrates updating page with ajax when text field value is changed

PageablesPage.title=Pageables Example
PageablesPage.description=shows ajax paging

RatingsPage.title=Ratings example
RatingsPage.description=shows a rating component.

TabbedPanelPage.title=Tabbed Panel Example
TabbedPanelPage.description=demonstrates ajax enabled tabbed panel

TodoList.title=Todo list Example
TodoList.description=shows ajax todo list page without writing any JavaScript

WorldClockPage.title=World Clock Example
WorldClockPage.description=demonstrates a single component with AjaxTimerBehavior updating multiple components

AjaxDownloadPage.title=Ajax Download
AjaxDownloadPage.description=download initiated via Ajax
