/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.wicket.request.mapper;

import java.util.List;

import org.apache.wicket.Application;
import org.apache.wicket.request.IRequestHandler;
import org.apache.wicket.request.IRequestMapper;
import org.apache.wicket.request.Request;
import org.apache.wicket.request.Url;
import org.apache.wicket.util.IProvider;
import org.apache.wicket.util.crypt.ICrypt;
import org.apache.wicket.util.string.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Request mapper that encrypts urls generated by another mapper.
 * 
 * @author igor.vaynberg
 */
public class CryptoMapper implements IRequestMapper
{
	private static final Logger log = LoggerFactory.getLogger(CryptoMapper.class);

	private final IRequestMapper wrappedMapper;
	private final IProvider<ICrypt> cryptProvider;
	private final Application application;

	/**
	 * Construct.
	 * 
	 * @param wrappedMapper
	 *            the non-crypted request mapper
	 * @param application
	 *            the current application
	 */
	public CryptoMapper(IRequestMapper wrappedMapper, Application application)
	{
		this(wrappedMapper, application, new ApplicationCryptProvider(application));
	}

	/**
	 * Construct.
	 * 
	 * @param wrappedMapper
	 *            the non-crypted request mapper
	 * @param application
	 *            the current application
	 * @param cryptProvider
	 *            the custom crypt provider
	 */
	public CryptoMapper(IRequestMapper wrappedMapper, Application application,
		IProvider<ICrypt> cryptProvider)
	{
		this.wrappedMapper = wrappedMapper;
		this.cryptProvider = cryptProvider;
		this.application = application;
	}

	public int getCompatibilityScore(Request request)
	{
		return 0;
	}

	public Url mapHandler(IRequestHandler requestHandler)
	{
		Url url = wrappedMapper.mapHandler(requestHandler);

		if (url == null)
		{
			return null;
		}

		return encryptUrl(url);
	}

	public IRequestHandler mapRequest(Request request)
	{
		Url url = decryptUrl(request, request.getUrl());

		if (url == null)
		{
			return null;
		}

		return wrappedMapper.mapRequest(request.cloneWithUrl(url));
	}

	private ICrypt getCrypt()
	{
		return cryptProvider.get();
	}


	private Url encryptUrl(Url url)
	{
		if (url.getSegments().isEmpty() && url.getQueryParameters().isEmpty())
		{
			return url;
		}
		String encryptedUrlString = getCrypt().encryptUrlSafe(url.toString());

		Url encrypted = new Url(url.getCharset());
		encrypted.getSegments().add(encryptedUrlString);
		encrypted.getQueryParameters().addAll(url.getQueryParameters());

		int numberOfSegments = url.getSegments().size();
		if (numberOfSegments == 0 && !url.getQueryParameters().isEmpty())
		{
			numberOfSegments = 1;
		}
		char[] encryptedChars = encryptedUrlString.toCharArray();
		int hash = 0;
		for (int segNo = 0; segNo < numberOfSegments; segNo++)
		{
			char a = encryptedChars[Math.abs(hash % encryptedChars.length)];
			hash++;
			char b = encryptedChars[Math.abs(hash % encryptedChars.length)];
			hash++;
			char c = encryptedChars[Math.abs(hash % encryptedChars.length)];

			String segment = "" + a + b + c;
			hash = hashString(segment);

			segment += String.format("%02x", Math.abs(hash % 256));
			encrypted.getSegments().add(segment);
			hash = hashString(segment);
		}

		return encrypted;
	}

	private Url decryptUrl(Request request, Url encryptedUrl)
	{
		if (encryptedUrl.getSegments().isEmpty() && encryptedUrl.getQueryParameters().isEmpty())
		{
			return encryptedUrl;
		}

		List<String> segments = encryptedUrl.getSegments();
		if (segments.size() < 2)
		{
			return null;
		}

		Url url = new Url(request.getCharset());
		try
		{
			String encryptedUrlString = segments.get(0);
			if (Strings.isEmpty(encryptedUrlString))
			{
				return null;
			}

			String decryptedUrl = getCrypt().decryptUrlSafe(encryptedUrlString);
			Url originalUrl = Url.parse(decryptedUrl, request.getCharset());

			int originalNumberOfSegments = originalUrl.getSegments().size();
			int numberOfSegments = encryptedUrl.getSegments().size();

			char[] encryptedChars = encryptedUrlString.toCharArray();
			int hash = 0;

			int segNo;
			for (segNo = 1; segNo < numberOfSegments && segNo < originalNumberOfSegments + 1; segNo++)
			{
				char a = encryptedChars[Math.abs(hash % encryptedChars.length)];
				hash++;
				char b = encryptedChars[Math.abs(hash % encryptedChars.length)];
				hash++;
				char c = encryptedChars[Math.abs(hash % encryptedChars.length)];

				String segment = "" + a + b + c;
				hash = hashString(segment);

				segment += String.format("%02x", Math.abs(hash % 256));
				hash = hashString(segment);

				if (segment.equals(encryptedUrl.getSegments().get(segNo)))
				{
					url.getSegments().add(originalUrl.getSegments().get(segNo - 1));
				}
				else
				{
					break;
				}
			}

			if (segNo < numberOfSegments)
			{
				url.getQueryParameters().addAll(encryptedUrl.getQueryParameters());

				for (; segNo < numberOfSegments; segNo++)
				{
					url.getSegments().add(encryptedUrl.getSegments().get(segNo));
				}
			}
			else
			{
				url.getQueryParameters().addAll(originalUrl.getQueryParameters());
			}
		}
		catch (Exception e)
		{
			log.error("Error decrypting URL", e);
			url = null;
		}

		return url;
	}

	private int hashString(final String str)
	{
		int hash = 97;

		for (char c : str.toCharArray())
		{
			int i = c;
			hash = 47 * hash + i;
		}

		return hash;
	}

	private static class ApplicationCryptProvider implements IProvider<ICrypt>
	{
		private final Application application;

		public ApplicationCryptProvider(Application application)
		{
			this.application = application;
		}

		public ICrypt get()
		{
			return application.getSecuritySettings().getCryptFactory().newCrypt();
		}
	}

}
