/*
 * $Id$
 * $Revision$
 * $Date$
 *
 * ====================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package wicket.examples.displaytag;

import java.util.List;

import wicket.PageParameters;
import wicket.examples.displaytag.utils.ListObject;
import wicket.examples.displaytag.utils.TableWithAlternatingRowStyle;
import wicket.examples.displaytag.utils.TestList;
import wicket.markup.html.basic.Label;
import wicket.markup.html.table.ListItem;
import wicket.markup.html.table.ListView;



/**
 * Simple table with a few columns
 * 
 * @author Juergen Donnerstag
 */
public class BasicColumns extends Displaytag
{
    /**
     * Constructor.
     * 
     * @param parameters Page parameters
     */
    public BasicColumns(final PageParameters parameters)
    {
        // test data
        List data = new TestList(6, false);
        
        // Add table of existing comments
        final ListView table = new TableWithAlternatingRowStyle("rows", data)
        {
            public void populateItem(final ListItem listItem)
            {
                final ListObject value = (ListObject) listItem.getModelObject();

                listItem.add(new Label("id", new Integer(value.getId())));
                listItem.add(new Label("name", value.getName()));
                listItem.add(new Label("email", value.getEmail()));
                listItem.add(new Label("status", value.getStatus()));
                listItem.add(new Label("comments", value.getDescription()));
            }
        };

        add(table);
 
        // This is a table component which "automatically" creates a table
        // including header based on JavaBean properties provided by the model object.
        final String[] headers = new String[] {"Id", "Name", "Email", "Status", "Description"};
        add(new TableGeneratorComponent("autogeneratedTable", data, headers, headers));
        
        // THis is a table containing all components of the page
        //add(new WicketComponentTree("componentTree", this.getPage()));
    }
}