#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
title=Template loaded by the page itself
explanation=<p> This page was loaded by a component specific override. You can use that - with care - if you have to implement custom loading strategies that are very local to the component. For instance, a custom component that loads it's template from a database and for which you don't want the application to have to know about it's differing loading resource. </p> <p> This example loads the custom template just once, though it may reload when resource polling is turned on and the template changes. If you want a load the template every time a page (or panel) is requested, you can additionally let your container implement IMarkupCacheKeyProvider, and then return null in the implementation of getCacheKey; Wicket will not cache templates without a cache key. This functionality can be used to e.g. when you want to load templates from a database, and you know that the actual templates can be different from request to request. </p>
