#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
title=Authentication and authorization
examples=authentication1,authentication2,authentication3,authorization
authentication1.title=authentication-1
authentication1.description=A very simple authentication example.
authentication2.title=authentication-2
authentication2.description=A little bit more advanced authentication example (using cookies).
authentication3.title=authentication-3
authentication3.description=Demonstrates authentication for pages.
authorization.title=authorization
authorization.description=Demonstrates authorization for pages and components.
