/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.wicket.core.util.crypt;

import java.security.SecureRandom;

import javax.crypto.SecretKey;

/**
 * A single, self-identifying authenticated encryption scheme.
 * <p>
 * Every scheme has a stable {@link #id()} that {@link SchemeCrypt} writes as a one-byte marker
 * in front of the ciphertext, so the correct scheme can be selected on decryption and matched
 * against a whitelist (downgrade protection). The marker is passed to {@link #encrypt} /
 * {@link #decrypt} as <em>additional authenticated data</em> ({@code aad}) so it is covered by
 * the authentication tag and cannot be altered to force a different scheme.
 * <p>
 * Schemes must use authenticated (AEAD) encryption: {@link #decrypt} returns {@code null} when
 * authentication fails. All keys are 256-bit AES {@link SecretKey}s generated by the factory;
 * schemes do not derive keys.
 * <p>
 * Implementations must be thread-safe and pick a unique, stable {@link #id()}. Wicket reserves
 * ids {@code 1..31}; custom schemes should use ids {@code >= 32}.
 */
public interface ICryptScheme
{
	/**
	 * @return the stable, unique one-byte marker identifying this scheme
	 */
	byte id();

	/**
	 * Encrypt the given plaintext.
	 *
	 * @param plaintext
	 *            the bytes to encrypt
	 * @param key
	 *            the secret key
	 * @param aad
	 *            additional authenticated data (the scheme marker); authenticated but not encrypted
	 * @param random
	 *            source of randomness for the nonce
	 * @return the ciphertext (including nonce and authentication tag)
	 */
	byte[] encrypt(byte[] plaintext, SecretKey key, byte[] aad, SecureRandom random);

	/**
	 * Decrypt the given ciphertext.
	 *
	 * @param ciphertext
	 *            the bytes produced by {@link #encrypt} (nonce + ciphertext + tag)
	 * @param key
	 *            the secret key
	 * @param aad
	 *            the additional authenticated data that was supplied on encryption (the marker)
	 * @return the decrypted plaintext, or {@code null} if authentication fails or the input is
	 *         malformed
	 */
	byte[] decrypt(byte[] ciphertext, SecretKey key, byte[] aad);
}
