#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
title=Template Example
explanation=<p class="dotted-box"> This example shows two different ways of building your page up from shared parts. The first example uses what we commonly call 'markup inheritence', and the second example shows how to achieve roughly the same using borders.<br /> &#160;&#160;Compare the examples and decides what works best for you. You will find that markup inheritance is usually easier to work with, and you'll rarely have the need to work with borders. But in some cases borders make sense, and can be a little bit more flexible.<br /> &#160;&#160;Also note the use of panels and component replacement to switch the banner. Component replacement can be a powerful alternative to navigating between pages. </p>
