#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
Index.title=Component Reference
LabelPage.title=wicket.markup.html.basic.Label
MultiLineLabelPage.title=wicket.markup.html.basic.MultiLineLabel
PanelPage.title=wicket.markup.html.panel.Panel
BorderPage.title=wicket.markup.html.border.Border
TabbedPanelPage.title=wicket.markup.html.tabs.TabbedPanel (wicket-extensions)
FragmentPage.title=wicket.markup.html.panel.Fragment
LinkPage.title=wicket.markup.html.link.Link
ExternalLinkPage.title=wicket.markup.html.link.ExternalLink
BookmarkablePageLinkPage.title=wicket.markup.html.link.BookmarkablePageLink
FormPage.title=wicket.markup.html.form.Form
ButtonPage.title=wicket.markup.html.form.Button
SubmitLinkPage.title=wicket.markup.html.form.SubmitLink
TextFieldPage.title=wicket.markup.html.form.TextField
TextAreaPage.title=wicket.markup.html.form.TextArea
CheckBoxPage.title=wicket.markup.html.form.CheckBox
CheckGroupPage.title=wicket.markup.html.form.CheckGroup, wicket.markup.html.form.Check, and wicket.markup.html.form.CheckGroupSelector
CheckGroupPage2.title=Embedded wicket.markup.html.form.CheckGroup, wicket.markup.html.form.Check, and wicket.markup.html.form.CheckGroupSelector
CheckBoxMultipleChoicePage.title=wicket.markup.html.form.CheckBoxMultipleChoice
CheckBoxSelectorPage.title=wicket.markup.html.form.CheckBoxSelector
DropDownChoicePage.title=wicket.markup.html.form.DropDownChoice
ListChoicePage.title=wicket.markup.html.form.ListChoice
RadioChoicePage.title=wicket.markup.html.form.RadioChoice
RadioGroupPage.title=wicket.markup.html.form.RadioGroup and wicket.markup.html.form.Radio
RadioGroupPage2.title=Embedded wicket.markup.html.form.RadioGroup and wicket.markup.html.form.Radio
ListMultipleChoicePage.title=wicket.markup.html.form.ListMultipleChoice
SelectPage.title=wicket.extensions.markup.html.form.select.Select
PalettePage.title=wicket.extensions.markup.html.palette.Palette
